name: Run Python Package
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: Install package from release
              run: |
                  PACKAGE_VERSION=$(curl --silent "https://api.github.com/repos/bwhite001/fuelprices-7eleven/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
                  pip install "https://github.com/bwhite001/fuelprices-7eleven/releases/download/${PACKAGE_VERSION}/https://github.com/bwhite001/fuelprices-7eleven/releases/download/0.1.0/fuelprices_7eleven-0.1.0.tar.gz"
            - name: Update PATH
              run: echo "$HOME/.local/bin" >> $GITHUB_PATH

            - name: Run Python script
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: python $HOME/.local/bin/fuelprices_discord
