name: Send Discord Notification
on:
    workflow_dispatch:
    schedule:
      - cron: '0 21 * * *' # Runs daily at 7am AEST (9pm UTC)
jobs:
    schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                cache: 'poetry'
            - run: poetry install
            - name: Install poetry packages
              run: poetry install --no-dev

            - name: Send Discord Notification
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: poetry run fuelprices_discord
